// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Link struct {
	ID           int64
	UserID       int64
	FilePath     string
	ExpiresAt    pgtype.Timestamptz
	MaxDownloads pgtype.Int4
	Downloads    pgtype.Int4
	CreatedAt    pgtype.Timestamptz
}

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}
